[node]
working_dir = "/tmp/stacks-node/devnet/"
rpc_bind = "0.0.0.0:20443" # TODO: make these ports random
p2p_bind = "0.0.0.0:20444" # TODO: make these ports random
miner = true
seed = "753b7cc01a1a2e86221266a154af739463fce51219d97e4f856cd7200c3bd2a601"
local_peer_seed = "753b7cc01a1a2e86221266a154af739463fce51219d97e4f856cd7200c3bd2a601"
pox_sync_sample_secs = 0
wait_time_for_blocks = 0
wait_time_for_microblocks = 50
microblock_frequency = 1000

[connection_options]
# inv_sync_interval = 10
# download_interval = 10
# walk_interval = 10
disable_block_download = true
disable_inbound_handshakes = true
disable_inbound_walks = true
public_ip_address = "1.1.1.1:1234"

[miner]
first_attempt_time_ms = 500
subsequent_attempt_time_ms = 1000
block_reward_recipient = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"

# These are addresses from https://github.com/stacks-network/stacks-blockchain#readme
[[ustx_balance]]
# Private key: b8d99fd45da58038d630d9855d3ca2466e8e0f89d3894c4724f0efc9ff4b51f001
address = "ST2ZRX0K27GW0SP3GJCEMHD95TQGJMKB7G9Y0X1MH"
amount = 100000000

[[ustx_balance]]
# Private key: 3a4e84abb8abe0c1ba37cef4b604e73c82b1fe8d99015cb36b029a65099d373601
address = "ST26FVX16539KKXZKJN098Q08HRX3XBAP541MFS0P"
amount = 100000000

[[ustx_balance]]
# Private key: 052cc5b8f25b1e44a65329244066f76c8057accd5316c889f476d0ea0329632c01
address = "ST3CECAKJ4BH08JYY7W53MC81BYDT4YDA5M7S5F53"
amount = 100000000

[[ustx_balance]]
# Private key: 9aef533e754663a453984b69d36f109be817e9940519cc84979419e2be00864801
address = "ST31HHVBKYCYQQJ5AQ25ZHA6W2A548ZADDQ6S16GP"
amount = 100000000

# Add stacks-api as an event observer
[[events_observer]]
endpoint = "stack-api.devnet:3700"
retry_count = 255
include_data_events = false
events_keys = ["*"]

[burnchain]
chain = "bitcoin"
mode = "krypton"
poll_time_secs = 1
timeout = 30
peer_host = "host.docker.internal"
rpc_ssl = false
wallet_name = "devnet"
username = "devnet"
password = "devnet"
rpc_port = 20445 # TODO: make random
peer_port = 18444 # TODO: make random
pox_2_activation = 109

[[burnchain.epochs]]
epoch_name = "1.0"
start_height = 0

[[burnchain.epochs]]
epoch_name = "2.0"
start_height = 100

[[burnchain.epochs]]
epoch_name = "2.05"
start_height = 102

[[burnchain.epochs]]
epoch_name = "2.1"
start_height = 106
