name: Clarinet
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    name: Clarinet check for sbtc-ops and sbtc-mini
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true

      - name: Install clarinet
        run: chmod +x ./bin/install_clarinet_action.sh && ./bin/install_clarinet_action.sh

      - name: Run clarinet check for sbtc-ops
        working-directory: ./sbtc-ops/clarinet
        run: clarinet check

      - name: Run clarinet test for sbtc-ops
        working-directory: ./sbtc-ops/clarinet
        run: clarinet test

      - name: Run unit tests for sbtc-mini
        working-directory: ./sbtc-mini
        run: ./scripts/test.sh

      - name: "Export sbtc-mini code coverage"
        uses: codecov/codecov-action@v1
        with:
          files: .coverage/lcov.info
          verbose: true